export default{
    //部门
    "offices":'/api/office/v1/offices',
    //用户
    "users":'/api/user/v1/users',
    //区域
    "area":'/api/area/v1/areas',
    //验证区域名称
    "areaNameDistinct":'/api/area/v1/roles/validate',
    //角色
    "role":'/api/role/v1/roles',
    //字典表
    "dict":'/api/dict/v1/dicts',
    //菜单
    "menu":'/api/menu/v1/menus',
    //日志
    "log":'/api/log/v1/logs',
    //参数
    "param":'/api/param/v1/params',
    //机构管理
    "org":'/api/org/v1/orgs',
    //动态字段
    "dynamicFields":'/api/dynamic-field/v1/dynamic-fields',
    //受理地点
    "acceptStation":'/api/accept-station/v1/accept-stations',
    //名字去重验证
    "acceptStationNameDistinct":'/api/accept-station/v1/roles/validate',
    //受理表单字段
    "acceptFormField":'/api/accept-form-field/v1/accept-form-fields',
    //顺序号设置
    "sequenceSetting":'/api/caSequence/v1/caSequences',
    //消息管理
    "msg":'/api/message/v1/messages'
}